USC-SIkJalpha Round 0 submission
covid19-forecast-hub-europe/covid19-scenario-hub-europe pull request #4
Opened 2022-03-14 22:21 UTC by scc-usc

2022-03-21 11:24 UTC, Bisaloo commented
Hi @scc-usc :wave:, thanks for your contribution!

There is one last difference with the format used in the US scenario hub you need to take into account. [As detected by our validation checks](https://github.com/covid19-forecast-hub-europe/covid19-scenario-hub-europe/runs/5551309853?check_suite_focus=true#step:6:19), the `horizon` column should not include the word `ahead`. This is also detailed in our [technical](https://github.com/covid19-forecast-hub-europe/covid19-scenario-hub-europe/wiki/Targets-and-horizons#date-format) [wiki](https://github.com/covid19-forecast-hub-europe/covid19-scenario-hub-europe/wiki/Submission-format#horizon-horizon).

This is how the first line of your csv file should change for example:

```diff
- 2022-03-13,A-2022-02-25,inc case,1 wk ahead,2022-03-19,AT,quantile,0.01,20339
+ 2022-03-13,A-2022-02-25,inc case,1 wk,2022-03-19,AT,quantile,0.01,20339
```

Please let me know if this is not clear and you have any questions :relaxed:

2022-03-21 16:19 UTC, scc-usc commented
Hi Hugo,

I have made the change. Thanks for catching it.

Ajitesh

2022-03-22 16:54 UTC, Bisaloo requested changes
Hi again, I've added a couple of comments to fix the yaml file structure and make sure it passes our validation.
There is a final issue with the `model_version` field that is currently not defined in our template. We are discussing if it's something we should add and I'll get back to you shortly with more information!

2022-03-22 16:54 UTC, Bisaloo commented on data-processed/USC-SIkJalpha/metadata-USC-SIkJalpha.txt
> +	[1] Ajitesh Srivastava, Tianjian Xu and Viktor K. Prasanna, "Fast and Accurate Forecasting of COVID-19 Deaths using the SIkJalpha Model". https://arxiv.org/abs/2007.05180.
```suggestion
citation: |
  [1] Ajitesh Srivastava, Tianjian Xu and Viktor K. Prasanna, "Fast and Accurate Forecasting of COVID-19 Deaths using the SIkJalpha Model". https://arxiv.org/abs/2007.05180.
```

2022-03-22 16:54 UTC, Bisaloo commented on data-processed/USC-SIkJalpha/metadata-USC-SIkJalpha.txt
> +methods_long: [Note that this is general description. Hospitalizaitons and age-groups are not applicable to European Scenario Modeling Hub] We use our own epidemic model called SI-kJalpha, preliminar
```suggestion
methods_long: |
  [Note that this is general description. Hospitalizaitons and age-groups are not applicable to European Scenario Modeling Hub] We use our own epidemic model called SI-kJalpha, preliminary version
```

2022-03-22 16:54 UTC, Bisaloo commented on data-processed/USC-SIkJalpha/metadata-USC-SIkJalpha.txt
> +calibration: All calibrations using regression. No manual-tuning other than the listed assumption and trivial settings: non-zero lag between infection and death.
```suggestion
calibration: 'All calibrations using regression. No manual-tuning other than the listed assumption and trivial settings: non-zero lag between infection and death.'
```

2022-03-22 16:54 UTC, Bisaloo commented on data-processed/USC-SIkJalpha/metadata-USC-SIkJalpha.txt
> +vaccine_immunity_duration: Only waning immunity is considered! The probability of transferring to partially immune state by at time t is modeled as a gamma distribution such that: (i) the median is a
```suggestion
vaccine_immunity_duration: 'Only waning immunity is considered! The probability of transferring to partially immune state by at time t is modeled as a gamma distribution such that: (i) the median is as per the scenario; (ii) the efficacy (given the partial immune protection against infection) after the first 60 days is the "initial" vaccine efficacy.'
```

2022-03-22 16:54 UTC, Bisaloo commented on data-processed/USC-SIkJalpha/metadata-USC-SIkJalpha.txt
> +model_abbr: USC-SI_kJalpha
```suggestion
model_abbr: USC-SIkJalpha
```

2022-03-22 16:54 UTC, Bisaloo commented on data-processed/USC-SIkJalpha/metadata-USC-SIkJalpha.txt
> +methods: Uses SIKJalpha which models temporally varying infection, death, and hospitalization rates. Learning is performed by reducing the problem to multiple simple linear regression problems. Effec
Methods should be under 200 characters. Feel free to expand in the `methods_long` section.

2022-03-22 16:54 UTC, Bisaloo commented on data-processed/USC-SIkJalpha/metadata-USC-SIkJalpha.txt
> +contract_tracing: Not applicable.
```suggestion
contact_tracing: Not applicable.
```

2022-03-28 09:38 UTC, Bisaloo commented
Hi @scc-usc, I have updated our validations to allow the `model_version` field. Would you have a moment to check at the commit suggestions I made to fix the metadata file format?

If you're busy and do not want to deal with it, I can do the changes myself (none of the actual content will change, it's just formatting).

2022-03-28 17:14 UTC, scc-usc commented on data-processed/USC-SIkJalpha/metadata-USC-SIkJalpha.txt
> +methods: Uses SIKJalpha which models temporally varying infection, death, and hospitalization rates. Learning is performed by reducing the problem to multiple simple linear regression problems. Effec
Hi Hugo. Sorry for the late response. I was traveling and now catching up with deadlines. I have accepted your suggestions. For this one, could you please remove the last sentence? 
Thanks,
Ajitesh

2022-03-29 09:37 UTC, Bisaloo approved these changes

2022-04-04 19:17 UTC, scc-usc commented
@Bisaloo : I just noticed that the validation had failed. But I also see "approved these changes". Do I need to resubmit or the submission has already been fixed?
Thanks,
Ajitesh

2022-04-07 15:41 UTC, Bisaloo commented
:wave: @scc-usc, yes, everything was fine when I approved the PR. 

However, the most recent changes have some issues though. From line 306177 onwards, the horizon column uses `1 wk ahead` instead of `1 wk`, as discussed in https://github.com/covid19-forecast-hub-europe/covid19-scenario-hub-europe/pull/4#issuecomment-1073779872. Would you like to fix it?

We are waiting for a couple more submissions are will probably merge them all together at this moment :slightly_smiling_face:

2022-04-11 07:08 UTC, merged